title: Odin
optionalCategoryIndex: true
supportedLanguages: []
properties: []
link:
  name: odin
  pathname: github.com/Smile-Tech-Study/helpOdin/main/-
  lastVisited: github.com/Smile-Tech-Study/helpOdin/main/-/struktura/disciplina
  logo: null
  title: odin
  query: {}
  group: null
  code: ""
  style: null
  description: null
  order: 999999
  isCloning: false
  cloneCancelDisabled: false
  redirectOnClone: null
relatedLinks: []
name: odin
repositoryName: helpOdin
sourceName: github.com
userInfo:
  mail: kitlove51@list.ru
  name: LyubovAsseyeva
  id: kitlove51@list.ru
logo: tempImageewbD2A.png
logo_dark: logo odin.png
